### ISSUE TITLE
Sync Record aborts and tries to sync all records within a table

### ISSUE THREAD

**Issue by designedbydave** [salcosta/vsc-servicenow-sync#7] opened 2018-02-21 19:04 UTC
I was trying to sync a new widget I made and using "Sync Record" in the explorer menu. After querying it aborts and asks if I want to sync a number of records. The only way I can sync a single record if I click on sync multiple records and escape it. This will bring up the menu to sync individual records.

https://d.pr/v/XMHp6u

I've attached a screen capture to show you the issue.

**Comment by mak42** [comment] 2018-02-22 11:33
Hello,

I had the same issue and already have a fix for it apparently I made some mistake making the pull request it is a single commit in a differnt pull request I did already before.

https://github.com/salcosta/vsc-servicenow-sync/pull/5/commits/7f5aaf5ad13598d25a1fb8d3181cb750961394a2

This commit will fix the issue, the problem is that vscode somehow changed the behavior of commands so the query parameter of the pullFile function is not undefined anymore.

If you want to apply this fix just go in your home directoy and then open the following file

> .vscode\extensions\anerrantprogrammer.servicenow-sync-0.1.2\extension.js

at line 251 replace the if else statement with the one in my commit.

**Comment by designedbydave** [comment] 2018-02-22 15:38
Hey @mak42, I did some digging of my own, from what I was able to see, an object is passed into 'query' in the pullFile function. You mentioned this in 7f5aaf5, and you're right about VScode passing query as an object. 

`0:Object
$mid:1
fsPath:"/Users/davidlam/Workspace/ServiceNow/devXXXXX/sp_widget/client_script"
external:"file:///Users/davidlam/Workspace/ServiceNow/dev40845/sp_widget/client_script"
path:"/Users/davidlam/Workspace/ServiceNow/devXXXXX/sp_widget/client_script"
scheme:"file"`

I updated the same line, but instead of flipping the logic and looking for 'string', I modified so typeof query should check to see if it is an object so listing records work. 

This commit should show my change  4c1594a

**Comment by salcosta** [comment] 2019-03-16 02:19
Ok found the fix for this, will be patching it shortly, sorry it took over a year.

**Closed as completed** 2019-03-17 01:35 UTC
